{% set name = "pyzenodo3" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyzenodo3-{{ version }}.tar.gz
  sha256: 6eb7a9766fbc1c7258c506508c918f667a5671cbeed1ff628f63a7438cbe2998

build:
  number: 1
  noarch: python
  entry_points:
    - search_zenodo = search_zenodo:main
    - upload_zenodo = upload_zenodo:main
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - beautifulsoup4
    - python >={{ python_min }}
    - requests

test:
  imports:
    - pyzenodo3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/space-physics/pyzenodo3
  summary: Pure Python 3 wrapper for the Zenodo REST API
  license: Apache-2.0
  license_file: LICENSE.txt
  description: >
    PyZenodo3 is a pure Python wrapper for the Zenodo REST API
    (http://developers.zenodo.org/). It allows upload to and download from
    Zenodo.
  doc_url: https://github.com/space-physics/pyzenodo3
  dev_url: https://github.com/space-physics/pyzenodo3

extra:
  recipe-maintainers:
    - Midnighter
    - eladnoor
